name: "Terraform Build and Deploy - ACC"

on:
  workflow_dispatch:

env:
  terraform_version: 1.7.0
  working_directory: ${{ github.workspace }}

#only run 1 concurrently
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write 
  contents: read
  pull-requests: write

jobs:
    prepare-env-acc:

      name: "Setup environment - acc"

      runs-on: 
        group: just-linux-runners-v2

      steps:
        - run: echo "null"

      outputs:
        environment: acc
        tf_dir: ${{ env.working_directory }}
        tf_version: ${{ env.terraform_version }}

    terraform-validate-and-build-acc:

      name: "TF Build"

      needs: [ prepare-env-acc ]

      uses: Just-Crossborder/JustOps/.github/workflows/terraform-reusable-validate-and-build.yml@tf-v0.0.1
      with:
        environment: ${{ needs.prepare-env-acc.outputs.environment }}
        tf_directory: ${{ needs.prepare-env-acc.outputs.tf_dir }}
        tf_version: ${{ needs.prepare-env-acc.outputs.tf_version }}
      secrets: inherit
    
    terraform-deploy-acc:
      # this job will only run if the PR has been merged / closed
      # if: github.event.pull_request.merged == true

      name: "TF Deploy"

      needs: [ prepare-env-acc, terraform-validate-and-build-acc ]

      uses: Just-Crossborder/JustOps/.github/workflows/terraform-reusable-deploy.yml@tf-v0.0.1
      with:
        environment: ${{ needs.prepare-env-acc.outputs.environment }}
        tf_directory: ${{ needs.prepare-env-acc.outputs.tf_dir }}
        tf_version: ${{ needs.prepare-env-acc.outputs.tf_version }}
      secrets: inherit